/* -------------------------------------------------------
   👤 User Type
   Represents a customer/user record in the POS.
------------------------------------------------------- */
import type { User } from "../../types/user";

/* -------------------------------------------------------
   🧱 userService
   Lightweight abstraction over user storage.

   Responsibilities:
   - find(): lookup by phone or email
   - create(): add a new user
   - login(): alias for find() to support auth modals
   - all(): return all stored users

   Now fully connected to the C# Backend & Profiles Table.
------------------------------------------------------- */

// Connect to the backend API for user management
const API = process.env.NEXT_PUBLIC_API_URL;

export const userService = {
  /* -------------------------------------------------------
     🔍 find()
     Lookup a user by phone OR email via the C# backend API.
     Returns null if not found.
  ------------------------------------------------------- */
  async find(value: string): Promise<User | null> {
    try {
      const res = await fetch(`${API}/api/profiles/find?value=${encodeURIComponent(value)}`);
      
      if (!res.ok) return null;
      
      return await res.json();
    } catch (err) {
      console.error("❌ Profile lookup failed:", err);
      return null;
    }
  },

  /* -------------------------------------------------------
     ➕ create()
     Create a new user record.
     - Saves a new customer directly into the 'Profiles' table.
  ------------------------------------------------------- */
  async create(data: {
    name?: string;
    phone?: string;
    email?: string;
  }): Promise<User> {
    const res = await fetch(`${API}/api/profiles`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(data),
    });

    if (!res.ok) {
      const errorText = await res.text();
      console.error("❌ Backend Error:", errorText);
      throw new Error("Failed to create customer profile in database.");
    }

    // Returns the new Profile object with the UUID generated by C#
    return await res.json();
  },
  
    /* -------------------------------------------------------
        🔄 update() 
        It uses PUT to modify an existing record by ID.
    ------------------------------------------------------- */
   async update(id: string, data: { 
  name?: string; 
  phone?: string; 
  email?: string;
  address?: string;
  city?: string;
  zip?: string;
}) {
  const res = await fetch(`${API}/api/profiles/${id}`, {
    method: "PUT", 
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  });
  return await res.json();
},

  /* -------------------------------------------------------
     🔑 login()
     Alias for find() used by the Online Shop LoginModal.
  ------------------------------------------------------- */
  async login(emailOrPhone: string): Promise<User | null> {
    return this.find(emailOrPhone);
  },

  /* -------------------------------------------------------
     📋 all()
     Return all stored users.
     Fetches the full master list from the Profiles table.
  ------------------------------------------------------- */
  async all(): Promise<User[]> {
    try {
      const res = await fetch(`${API}/api/profiles`);
      if (!res.ok) return [];
      return await res.json();
    } catch (err) {
      console.error("❌ Failed to fetch all profiles:", err);
      return [];
    }
  },
};